# SPDX-License-Identifier: Apache-2.0
"""tools/build [module]: rebuild the kernels when C++ or build files changed.

All kernels form one extension module, splintercam._kernels, so a module argument is only checked,
and everything is built. `uv sync` rebuilds the editable install when a file listed under
[tool.uv] cache-keys in pyproject.toml changed; CMake then recompiles only what changed.

It then regenerates the type stubs of the kernels in src/splintercam/_kernels/ with nanobind's
stubgen, so pyright sees the kernel API. They are committed, so a change of a kernel signature
shows up in review; the compiled module, not this stub folder, is what Python imports.
"""

import argparse
import shutil
import sys
from collections.abc import Sequence

from modules import check_module
from runner import ROOT, Status, StepResult, UsageError, finish, run_step, usage_error

STUB_DIR = ROOT / "src" / "splintercam" / "_kernels"
STUB_HEADER = (
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.\n"
)


def _regenerate_stubs() -> StepResult:
    shutil.rmtree(STUB_DIR, ignore_errors=True)  # drops stubs of removed kernels
    argv = [sys.executable, "-m", "nanobind.stubgen", "-q", "-r", "-m", "splintercam._kernels"]
    result = run_step("kernel stubs", [*argv, "-O", "src/splintercam"], reproduce="tools/build")
    if result.status is Status.PASS:
        for stub in sorted(STUB_DIR.glob("*.pyi")):
            stub.write_text(STUB_HEADER + stub.read_text(encoding="utf-8"), encoding="utf-8")
    return result


def build_step() -> StepResult:
    """`uv sync`, then the kernel stubs; one step for tools/check and tools/test-one."""
    sync = run_step("build", ["uv", "sync", "--locked"], reproduce="tools/build")
    if sync.status is not Status.PASS:
        return sync
    stubs = _regenerate_stubs()
    seconds = sync.seconds + stubs.seconds
    return StepResult("build", stubs.status, seconds, stubs.detail)


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(prog="tools/build", description=__doc__)
    parser.add_argument("module", nargs="?", help="a module name, for example geometry2d")
    args = parser.parse_args(argv)
    try:
        if args.module is not None:
            check_module(args.module)
        return finish("build", [build_step()])
    except UsageError as error:
        return usage_error("build", error)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
