# SPDX-License-Identifier: Apache-2.0
"""tools/size-check: the file, function and module size limits of docs/dev/12, section 3.

Soft limits are reported, hard limits fail:
- file (Python or C++): over 400 lines reported, over 800 fails; generated files are excepted;
- Python function: over 60 lines reported; its hard limits and those of C++ functions are ruff's
  and clang-tidy's, in tools/lint, once docs/plans/active/0001-protected-changes.patch is applied;
- module: the NLOC of src/splintercam/<module>/ against its `budget` in architecture/modules.yaml,
  reported over the budget, failing over the budget + 20 %; a module with code but no budget is
  reported.

NLOC counts the lines that hold code, as lizard does (docs/dev/12, section 3): Python lines with a
token other than a comment, docstrings and other bare strings left out; C++ lines that are not
blank and do not start with //. A file that cannot be read as UTF-8 or parsed fails.
"""

import argparse
import ast
import io
import sys
import time
import tokenize
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from modules import module_budgets
from runner import ROOT, Status, StepResult, finish, git_files

# The limits of docs/dev/12, section 3: declared tool settings, changed only by decision (D-139).
FILE_SOFT_LINES = 400
FILE_HARD_LINES = 800
FUNCTION_SOFT_LINES = 60
MODULE_HARD_FACTOR = 1.2

PYTHON_SUFFIXES = frozenset({".py", ".pyi"})
CPP_SUFFIXES = frozenset({".cpp", ".hpp", ".h"})
# docs/dev/04: generated code starts with "Generated by <tool> from <source>. Do not edit."
GENERATED_HEAD_LINES = 3
NON_CODE_TOKENS = frozenset(
    {tokenize.COMMENT, tokenize.NL, tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT}
    | {tokenize.ENDMARKER}
)


@dataclass(frozen=True, slots=True)
class Finding:
    fails: bool
    text: str


def is_generated(lines: Sequence[str]) -> bool:
    head = lines[:GENERATED_HEAD_LINES]
    return any("Generated by" in line and "Do not edit." in line for line in head)


def file_findings(path: Path, lines: Sequence[str]) -> list[Finding]:
    if is_generated(lines) or len(lines) <= FILE_SOFT_LINES:
        return []
    fails = len(lines) > FILE_HARD_LINES
    limit = FILE_HARD_LINES if fails else FILE_SOFT_LINES
    return [Finding(fails, f"{_name(path)}: {len(lines)} lines, over {limit}")]


def function_findings(path: Path, source: str) -> list[Finding]:
    findings: list[Finding] = []
    for node in ast.walk(ast.parse(source, filename=str(path))):
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            length = (node.end_lineno or node.lineno) - node.lineno + 1
            if length > FUNCTION_SOFT_LINES:
                where = f"{_name(path)}:{node.lineno} {node.name}"
                findings.append(
                    Finding(False, f"{where}: {length} lines, over {FUNCTION_SOFT_LINES}")
                )
    return findings


def nloc(path: Path, source: str) -> int:
    if path.suffix in CPP_SUFFIXES:
        stripped = (line.strip() for line in source.splitlines())
        return sum(1 for line in stripped if line and not line.startswith("//"))
    lines: set[int] = set()
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type not in NON_CODE_TOKENS:
            lines.update(range(token.start[0], token.end[0] + 1))
    for node in ast.walk(ast.parse(source, filename=str(path))):
        # A string as a whole statement: a docstring, or the documentation of an attribute.
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str):
                lines.difference_update(range(node.lineno, (node.end_lineno or node.lineno) + 1))
    return len(lines)


def module_findings(module: str, budget: int | None, size: int) -> list[Finding]:
    if budget is None:
        return [Finding(False, f"module {module}: {size} NLOC, no budget in modules.yaml")]
    if size <= budget:
        return []
    fails = size > budget * MODULE_HARD_FACTOR
    over = "its budget + 20 %" if fails else "its budget"
    return [Finding(fails, f"module {module}: {size} NLOC, over {over} of {budget}")]


def _name(path: Path) -> str:
    return path.relative_to(ROOT).as_posix() if path.is_relative_to(ROOT) else path.as_posix()


def source_findings(path: Path) -> tuple[list[Finding], int]:
    """The findings of one source file and its NLOC; a generated file has neither."""
    try:
        source = path.read_text(encoding="utf-8-sig")  # -sig: a byte-order mark is not code
        lines = source.splitlines()
        if is_generated(lines):
            return [], 0
        findings = file_findings(path, lines)
        if path.suffix == ".py":
            findings += function_findings(path, source)
        return findings, nloc(path, source)
    except (SyntaxError, ValueError, tokenize.TokenError) as error:  # ValueError: bad UTF-8
        return [Finding(True, f"{_name(path)}: cannot be read or parsed: {error}")], 0


def size_findings() -> list[Finding]:
    listing = git_files("ls-files", "--cached", "--others", "--exclude-standard")
    sources = [path for path in listing if path.suffix in PYTHON_SUFFIXES | CPP_SUFFIXES]
    budgets = module_budgets()
    package = ROOT / "src" / "splintercam"
    module_nloc: dict[str, int] = {}
    findings: list[Finding] = []
    for path in sources:
        file_result, size = source_findings(path)
        findings += file_result
        module = next((name for name in budgets if path.is_relative_to(package / name)), None)
        if module is not None:
            module_nloc[module] = module_nloc.get(module, 0) + size
    for module in sorted(module_nloc):
        findings += module_findings(module, budgets[module], module_nloc[module])
    return findings


def size_check_step() -> StepResult:
    """One step for tools/check: fails over a hard limit and reports the soft ones."""
    start = time.perf_counter()
    findings = size_findings()
    for finding in findings:
        print(f"{'FAIL' if finding.fails else 'REPORT'}  {finding.text}", flush=True)
    seconds = time.perf_counter() - start
    failed = sum(finding.fails for finding in findings)
    detail = f"{len(findings) - failed} reported"
    if failed:
        detail = f"{failed} over a hard limit, {detail}; reproduce: tools/size-check"
        return StepResult("size-check", Status.FAIL, seconds, detail)
    return StepResult("size-check", Status.PASS, seconds, detail)


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(prog="tools/size-check", description=__doc__)
    parser.parse_args(argv)
    return finish("size-check", [size_check_step()])


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
