# SPDX-License-Identifier: Apache-2.0
"""Tests of `tools/size-check --change`: the per-pull-request limit of docs/dev/12, section 3
(plan 0002, step 1).

Infrastructure only: no requirement covers the tools, so these tests carry no `req` marker.
"""

import subprocess
from pathlib import Path

import pytest

from cmd_size_check import added_lines, change_findings

GENERATED = "# SPDX-License-Identifier: Apache-2.0\n# Generated by tool from x. Do not edit.\n"


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)


def _write(repo: Path, name: str, text: str) -> None:
    path = repo / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _lines(count: int, word: str = "x") -> str:
    return "".join(f"{word}{i} = {i}\n" for i in range(count))


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A repository with one commit on `base` and a branch `work` checked out."""
    _git(tmp_path, "init", "-q", "-b", "base")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")
    _write(tmp_path, "src/old.py", _lines(300))
    _write(tmp_path, "src/moved.py", _lines(50, "m"))
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-q", "-m", "base")
    _git(tmp_path, "checkout", "-q", "-b", "work")
    return tmp_path


def _commit(repo: Path) -> None:
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "work")


def test_counts_added_lines_of_code_only(repo: Path) -> None:
    _write(repo, "src/new.py", _lines(5))
    _write(repo, "tests/test_new.py", _lines(100))
    _write(repo, "testdata/case.json", _lines(40))
    _write(repo, "docs/note.md", _lines(50))
    _write(repo, "src/stub.pyi", GENERATED + _lines(30))
    (repo / "src" / "image.bin").write_bytes(bytes(range(256)))
    _commit(repo)
    count, binaries = added_lines("base", repo)
    assert count == 5
    assert binaries == ["src/image.bin"]


def test_removed_lines_do_not_count(repo: Path) -> None:
    _write(repo, "src/old.py", _lines(10))
    _commit(repo)
    assert added_lines("base", repo) == (0, [])


def test_a_renamed_file_counts_only_its_changed_lines(repo: Path) -> None:
    _git(repo, "mv", "src/moved.py", "src/renamed.py")
    _write(repo, "src/renamed.py", _lines(50, "m") + "extra = 1\n")
    _commit(repo)
    assert added_lines("base", repo) == (1, [])


def test_commits_on_the_base_after_the_branch_point_do_not_count(repo: Path) -> None:
    _write(repo, "src/mine.py", _lines(3))
    _commit(repo)
    _git(repo, "checkout", "-q", "base")
    _write(repo, "src/theirs.py", _lines(500))
    _commit(repo)
    _git(repo, "checkout", "-q", "work")
    assert added_lines("base", repo) == (3, [])


@pytest.mark.parametrize(
    ("added", "fails", "reported"), [(200, False, False), (201, False, True), (400, False, True)]
)
def test_soft_limit_reports_and_hard_limit_holds(added: int, fails: bool, reported: bool) -> None:
    findings = change_findings(added, [], large_change=False)
    assert bool(findings) is reported
    assert all(finding.fails is fails for finding in findings)


def test_over_400_fails_unless_labelled_large_change() -> None:
    (finding,) = change_findings(401, [], large_change=False)
    assert finding.fails
    (labelled,) = change_findings(401, [], large_change=True)
    assert not labelled.fails
    assert "large-change" in labelled.text


def test_binary_files_are_named() -> None:
    (finding,) = change_findings(0, ["a.png"], large_change=False)
    assert not finding.fails
    assert "a.png" in finding.text
