# SPDX-License-Identifier: Apache-2.0
"""Tests of tools/size-check: the limits of docs/dev/12, section 3 (plan 0001, step 3).

Infrastructure only: no requirement covers the tools, so these tests carry no `req` marker.
"""

from pathlib import Path

import modules
import pytest
from cmd_size_check import file_findings, function_findings, module_findings, nloc


def _lines(count: int) -> list[str]:
    return [f"x{i} = {i}" for i in range(count)]


def test_a_file_of_400_lines_passes_and_one_of_401_is_reported() -> None:
    assert file_findings(Path("a.py"), _lines(400)) == []
    (finding,) = file_findings(Path("a.py"), _lines(401))
    assert not finding.fails
    assert "401 lines" in finding.text


def test_a_file_over_800_lines_fails() -> None:
    assert not file_findings(Path("a.py"), _lines(800))[0].fails
    assert file_findings(Path("a.py"), _lines(801))[0].fails


def test_a_generated_file_is_excepted() -> None:
    header = ["# SPDX-License-Identifier: Apache-2.0", "# Generated by tool from x. Do not edit."]
    assert file_findings(Path("a.pyi"), header + _lines(900)) == []


def test_a_python_function_over_60_lines_is_reported_not_failed() -> None:
    def function(name: str, body_lines: int) -> str:
        return f"def {name}() -> None:\n" + "    pass\n" * body_lines

    source = function("short", 59) + function("long", 60)
    (finding,) = function_findings(Path("a.py"), source)
    assert not finding.fails
    assert "long: 61 lines" in finding.text


def test_nloc_counts_code_and_docstrings_not_comments_or_blank_lines() -> None:
    source = '"""Doc\nstring."""\n\n# comment\nx = (\n    1\n)  # trailing\n'
    assert nloc(Path("a.py"), source) == 5
    assert nloc(Path("a.cpp"), "// comment\n\nint f() {\n  return 1;\n}\n") == 3


def test_a_module_over_its_budget_is_reported_and_over_120_percent_fails() -> None:
    assert module_findings("m", 100, 100) == []
    assert not module_findings("m", 100, 120)[0].fails
    assert module_findings("m", 100, 121)[0].fails


def test_a_module_without_budget_is_reported() -> None:
    (finding,) = module_findings("m", None, 10)
    assert not finding.fails
    assert "no budget" in finding.text


def test_module_budgets_are_read_from_modules_yaml(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    yaml = tmp_path / "modules.yaml"
    yaml.write_text(
        "modules:\n"
        "  foundation:             { layer: 0, depends_on: [], budget: 360 }\n"
        "  strategies/pocket:      { layer: 3, depends_on: [foundation] }\n"
        "kernel_libraries:\n"
        "  clipper2:      { licence: BSL-1.0, budget: 1 }\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(modules, "MODULES_YAML", yaml)
    assert modules.module_budgets() == {"foundation": 360, "strategies/pocket": None}
