# SPDX-License-Identifier: Apache-2.0
# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.
"""
C++ compute kernels of splintercam (ADR 0004).
Only each module's own Python code calls its submodule (docs/dev/03, rule 3).
"""

from splintercam._kernels import (
    geometry2d as geometry2d,
    offset2d as offset2d
)
