# SPDX-License-Identifier: Apache-2.0
# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.
from typing import Annotated

import numpy
from numpy.typing import NDArray


def two_sums(a: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')], y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """Write x + y = a + b exactly (REQ-G2D-016)."""

def two_products(a: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')], y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """Write x + y = a * b exactly (REQ-G2D-016)."""

def orient2d_signs(a: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], b: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], c: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """Write the exact sign of orient2d per row (REQ-G2D-007)."""

def incircle_signs(a: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], b: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], c: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], d: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """Write the exact sign of incircle per row (REQ-G2D-011)."""

def in_arc_circle_signs(q: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], centre: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], p0: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """Write the exact sign of |p0 - c|^2 - |q - c|^2 per row (REQ-G2D-022)."""

def vertical_extent_signs(q_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], centre: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], p0: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """
    Write the exact sign of (q_y - c_y)^2 - |p0 - c|^2 per row (REQ-G2D-023).
    """

def circles_through(p1: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], p2: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], p3: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], length_eps_mm: float, centres: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu')], radii: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')], found: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """
    Write per row the circle through p1, p2, p3, or found = 0 (REQ-G2D-097 to 101).
    """

def loop_area(rows: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], centre_x: float, centre_y: float, exact: bool) -> tuple[float, float]:
    """
    Return the signed area and the length of one loop of curve rows (REQ-G2D-128 to 132).
    """

def phi_minus_sin(phi: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """
    Write phi - sin(phi) per value, from basic operations only (REQ-G2D-018).
    """

def check_arcs(rows: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], length_eps_mm: float, out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """
    Write per curve row 0 (consistent), 1 (P1 off the circle) or 2 (sweep does not fit).
    """

def basic_atan2(y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """The arctangent the kernel decides with, for tests (REQ-G2D-018)."""

def arc_steps(arc: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], t_mm: float, inscribed: bool, max_step_rad: float) -> int:
    """
    The number of steps of the arc flattened within t (research 01, Flattening).
    """

def flatten_arc(arc: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], steps: int, inscribed: bool, out: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu')]) -> None:
    """Write the arc flattened in `steps` steps, inscribed or circumscribed."""
