# SPDX-License-Identifier: Apache-2.0
# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.
from typing import Annotated

import numpy
from numpy.typing import NDArray


def check_arcs(rows: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], length_eps_mm: float, out: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """
    Write per curve row 0 (consistent), 1 (P1 off the circle) or 2 (sweep does not fit).
    """

def basic_atan2(y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu', writable=False)], out: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C', device='cpu')]) -> None:
    """The arctangent the kernel decides with, for tests (REQ-G2D-018)."""

def arc_steps(arc: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], t_mm: float, inscribed: bool, max_step_rad: float) -> int:
    """
    The number of steps of the arc flattened within t (research 01, Flattening).
    """

def flatten_arc(arc: Annotated[NDArray[numpy.float64], dict(shape=(None, 7), order='C', device='cpu', writable=False)], steps: int, inscribed: bool, out: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu')]) -> None:
    """Write the arc flattened in `steps` steps, inscribed or circumscribed."""
