# SPDX-License-Identifier: Apache-2.0
# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.
from collections.abc import Sequence
from typing import Annotated

import numpy
from numpy.typing import NDArray


def offset_loops(points: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], loop_starts: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], id_points: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu', writable=False)], id_starts: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], source_ids: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu', writable=False)], classes: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C', device='cpu', writable=False)], offset: Sequence[float], grid: Sequence[float], points_out: Annotated[NDArray[numpy.float64], dict(shape=(None, 2), order='C', device='cpu')], starts_out: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu')], ids_out: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C', device='cpu')], fixed_out: Annotated[NDArray[numpy.uint8], dict(shape=(None,), order='C', device='cpu')]) -> tuple[int, int, int]:
    """
    Offset flattened, normalised loops in one Clipper2 call (offset = delta, a in mm, the bias and the rounding margin in grid units; grid = u, the span limit, the join step limit, eps_len; classes per vertex as D-059 orders them); return (status, points, loops), the counts it needed.
    """
