# SPDX-License-Identifier: Apache-2.0
# Generated by tools/build (nanobind stubgen) from the kernels. Do not edit.
"""
C++ compute kernels of splintercam (ADR 0004).
Only each module's own Python code calls its submodule (docs/dev/03, rule 3).
"""
